version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run Test and Coverage
          command: |
            npm test -- --coverage
      - codecov/upload:
          file: {{ coverage/lcov-report }}
